# Generated by Django 4.0.6 on 2022-07-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=2)),
                ('Gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=5)),
                ('Mob_no', models.BigIntegerField()),
            ],
        ),
    ]
